name: Upload to S3 and Download Locally

on:
  push:
    branches:
      - main

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload cat.png to S3
        run: |
          aws s3 cp ./Download/pipeline/ci-cd-pipeline-wth-s3/picture/cat.png s3://my-github-actions-bucket/

  download-from-s3:
    runs-on: ubuntu-latest
    needs: upload-to-s3
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download cat.png from S3 to specified folder
        run: |
          mkdir -p ./Download/pipeline/ci-cd-pipeline-wth-s3/picture/
          aws s3 cp s3://my-github-actions-bucket/cat.png ./Download/pipeline/ci-cd-pipeline-wth-s3/picture/cat.png
